[[accounts]]
email = "idyllic4202@wplacetools.com"
mobile = ""
area_code = ""
password = "test12345"

[[accounts]]
email = "espialeilani+grace@gmail.com"
mobile = ""
area_code = ""
password = "test12345"

[[accounts]]
email = "ar.r.o.g.anc.e.p.c.hz.xp@gmail.com"
mobile = ""
area_code = ""
password = "test12345"

[[accounts]]
email = "theobald2798+gladden@gmail.com"
mobile = ""
area_code = ""
password = "test12345"

[[accounts]]
email = "vj.zh.z.h.d.b.b.d.udhj.db@gmail.com"
mobile = ""
area_code = ""
password = "test12345"

[deepseek]
api_base = "https://chat.deepseek.com/api/v0"
wasm_url = "https://fe-static.deepseek.com/chat/static/sha3_wasm_bg.7b9ca65ddd.wasm"
user_agent = "DeepSeek/2.0.4 Android/35"
client_version = "2.0.4"
client_platform = "android"
client_locale = "zh_CN"
model_types = [
    "default",
    "expert",
]
max_input_tokens = [
    1048576,
    1048576,
]
max_output_tokens = [
    384000,
    384000,
]
model_aliases = []

[deepseek.tool_call]
extra_starts = [
    "<|tool_call_begin|>",
    "<tool_calls>",
    "<tool_call>",
]
extra_ends = [
    "<|tool_call_end|>",
    "</tool_calls>",
    "</tool_call>",
]

[server]
host = "127.0.0.1"
port = 22217
cors_origins = ["http://localhost:22217"]

[proxy]

[admin]
password_hash = "$2b$12$JhfD18V4o.vFiSpVCZPj8OXGs7yuT7b0X1v6IOI7db.3P0iaDEEku"
jwt_secret = "0433ae158b554461e09c06c0ec127b3b1909850b0f53f05602d2eb24ee4b39c2"
jwt_issued_at = 1777975160

[[api_keys]]
key = "sk-test"
description = "开发测试"
